#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-FromANSI
version:      1.01
version_from: lib/HTML/FromANSI.pm
installdirs:  site
requires:
    Test::More:                    0.11
    Term::VT102:                   0.01
    HTML::Entities:                0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_04
